### PR TITLE
added code of conduct

### PR DESCRIPTION
**Pull request by javier**
I have added the code of conduct copied from https://github.com/confcodeofconduct/confcodeofconduct.com

Not sure if style/contents are acceptable for you, but it's a start :)

### CODE REVIEW

**Comment by ccoloma** [comment]
Thanks! ^_^

**Comment by islomar** [comment]
First of all: I really appreciate the will of trying to do something good, which I'm sure it is in the base of this code. So, thank you for that, Javier.

Having said that, I would like to express my opinion about this: I don't I like AT ALL several parts of this code of conduct.

Too many points focused on sex. Too many "christianity echoes" there. There are lots of things which are much more offensive for me than sex, for example violence images against any kind of human being (and nothing is said about it). And I am not vegetarian, but what about images of meat?

It is not that I am against a Code of Conduct (though I have serious doubts about this way of "educating"), but IMHO it should be much more based on general sensitivity and RESPECT (a word which doesn't appear at all in the text, I don't get it).

Just to mention how absurd it sounds to me some things: what does "sexualised clothing" mean? Are trousers a sexualised clothing for men? Or skirts for women? Writing down so abstract "rules" is worse than saying nothing. Let's be serious, please.
Or that "inappropriate physical contact". Does it include a lovely couple who are kissing each other? If not, what does exactly mean and why to write down anything at all?

I am fully aware about how uncomfortable feel some women in our industry (and any other) with offensive language typically used by some people. That should be fixed, but I don't think this is the way  to go.

On the other hand: do we really what to get into the black area of censoring anything which might be offensive for someone? For example: would it be offensive a slide showing two nuns playing tennis? I'm sure that lots of nuns would find it funny (I knew some), while some people in the room might feel offended. How many people is needed to consider that something is offensive? One? One hundred? One million?

This CoC sounds so American to me...

Just my "humble opinion" and just saying: I wouldn't go again to a conference with this kind of CoC.
So I really hope that, in case we really think that we need one, it can be really different.

And again: thank you for moving things and the will to improve.

**Comment by icoloma** [comment]
We appreciate the feedback, but given that we are just copying verbatim the contents from https://github.com/confcodeofconduct/confcodeofconduct.com, your comments should probably be addressed directly to the original repository, not here. 

Anyway, I have failed to identify the sexuality bias on the contents:

> Harassment includes offensive verbal comments related to gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, ethnicity, religion, sexual images in public spaces, deliberate intimidation, stalking, following, harassing photography or recording, sustained disruption of talks or other events, inappropriate physical contact, and unwelcome sexual attention. 

Any explicit mention to sex should be related to the fact that the majority of reported complains have been related to sexually offensive behavior and sexually explicit images, the later to be expected when a marketing company addresses a community that is 90% male. About the contents sounding "American", I don't share that perception - but in any case @rem is British.

To some of the most ambiguous contents like "sexualised clothing/uniforms/costumes" or "inappropriate contact", common sense applies: [I know it when I see it](https://en.wikipedia.org/wiki/I_know_it_when_I_see_it). Ambiguous language is required when there is no way of compiling a set of explicit rules that cover all possible cases.

**Comment by islomar** [comment]
Hi Nacho.

First of all, thanks for your answer and opinions.

The reason why I wrote it here, it is because this is supposed to be a start for the CoC for the Codemotion in Spain. I don't mind the general declaration and where it is used, since each person/community is free to take the decision they want. 
I give my opinion here, and not there, because this is the one which would affect me and the community where I belong, in a very explicit and direct way.

I knew as well that the original writers/idea of this CoC don't come from USA. It's more about culture than about nationalities.

And finally, yes, I confess that I really hate that "I know it when I see it" philosophy (the last time I read it was in the Apple rules to accept an app in the Apple Store... it really shocked me). Common sense is subjective, so either we are explicit, or it is better not to say anything so "specifically generic", and let people self-regulate.

But obviously, all this is just my personal opinion :-)

**Comment by javier** [comment]
Hi. Thanks for commenting and for understanding my motivation for this is to make something good :)

Of course I respect your point of view, and I would really welcome any changes you deem appropriate to the suggested code. Rather than writing one from scratch I took one who has been used in several conferences already, but you are right. There are other codes and I consider different ones before picking this particular one.

Regarding "christianity" I wouldn't know what to say, as I don't believe in any gods at all. About the "sexualised clothing", I have attended professional events where sponsors used women dressed in a way not according to the rest of the conference in an effort to attract men to their stands. To me that's sexualised and since that is something that happens at conferences, and I think it sends the wrong message, I am all against that. You say this doesn't happen here.. we are in Spain. Really? look at this example of the Mobile World Congress in Barcelona http://www.google.co.uk/imgres?imgurl=http://s.wsj.net/public/resources/images/OB-MP051_cbos02_E_20110216061754.jpg&imgrefurl=http://blogs.wsj.com/tech-europe/2011/02/16/who-would-have-guessed-sex-sells/&h=239&w=359&tbnid=7IfuiMKVQaqAMM:&zoom=1&docid=7PJmjeP3BTltsM&ei=Hf2jVaahMKfd7QbZxoHYDw&tbm=isch&ved=0CCcQMygHMAdqFQoTCOaj_6fY2MYCFadu2wodWWMA-w  

Another subject you touch is "inappropriate physical contact" and you mention a lovely couple kissing each other. Well, that's not inappropriate at all. Inappropriate is when you cannot attend the after party in one event because you are afraid someone will try to touch you without your consent. Inappropriate is when a man walks to a woman and says "you look hot, i like programmer women" and the woman says "I am sorry but I am married and I am not here to flirt" and the man goes "oh, but is your husband here? I am not jealous".. I have seen that at a conference in Spain too. Hardly welcoming for women.

Codemotion last year held a panel discussing why there are not more women in technology. Well, there are a lot of reasons for that, but being a community that indulges in macho behaviour doesn't help at all.

I believe a code of conduct must unequivocally state that is not acceptable to discriminate anyone, and that everyone should feel welcome to attend your event. It should also state that anyone not behaving in an appropriate manner will be expelled. Maybe by  stating clearly your intentions you will attract more diversity to your event. What it's clear to me is that by doing nothing we will only have the imbalance that we have right now, where you barely see a 2% of women in one of the biggest conferences in Spain. I think it's broken, and I want to fix it.

If you want to contribute and change the wording of the code of conduct, you are very welcome to do so. But by comparing discrimination against women to discrimination against people who don't like to see images of meat I don't really think you are helping towards the solution

**Pull request merged**
