### PR TITLE
Fix typo in volunteer page

### PR DESCRIPTION
**Pull request by lmivan**

### CODE REVIEW

**Comment by icoloma** [comment]
Aren't they synonyms? https://en.wikipedia.org/wiki/Promotional_merchandise

I've had this same conversation in the past with someone else. Is `swag` more common? Not in my experience, but I am interested.

**Comment by lmivan** [comment]
I didn't noticed that, I've always used the word _swag_ and in all the conferences I've been they always use that word.

And also, If you google for _schwag_ https://www.google.es/search?q=schwag you'll see that the firsts results are "low grade marijuana" and I think you're not give that to the volunteers :stuck_out_tongue_winking_eye: 

There's also a nice explanation here: http://english.stackexchange.com/questions/45189/free-stuff-swag-or-schwag.

**Comment by icoloma** [comment]
The more you know :) 

Thanks!

**Comment by lmivan** [comment]
Yeah! :+1:

**Pull request merged**
